//! Helpers for formatting USN reason bitfields.

use windows::Win32::System::Ioctl::{
    USN_REASON_BASIC_INFO_CHANGE, USN_REASON_CLOSE, USN_REASON_COMPRESSION_CHANGE,
    USN_REASON_DATA_EXTEND, USN_REASON_DATA_OVERWRITE, USN_REASON_DATA_TRUNCATION,
    USN_REASON_DESIRED_STORAGE_CLASS_CHANGE, USN_REASON_EA_CHANGE, USN_REASON_ENCRYPTION_CHANGE,
    USN_REASON_FILE_CREATE, USN_REASON_FILE_DELETE, USN_REASON_HARD_LINK_CHANGE,
    USN_REASON_INDEXABLE_CHANGE, USN_REASON_INTEGRITY_CHANGE, USN_REASON_NAMED_DATA_EXTEND,
    USN_REASON_NAMED_DATA_OVERWRITE, USN_REASON_NAMED_DATA_TRUNCATION, USN_REASON_OBJECT_ID_CHANGE,
    USN_REASON_RENAME_NEW_NAME, USN_REASON_RENAME_OLD_NAME, USN_REASON_REPARSE_POINT_CHANGE,
    USN_REASON_SECURITY_CHANGE, USN_REASON_STREAM_CHANGE, USN_REASON_TRANSACTED_CHANGE,
};

const REASON_FLAGS: &[(u32, &str)] = &[
    (USN_REASON_DATA_OVERWRITE, "DATA_OVERWRITE"),
    (USN_REASON_DATA_EXTEND, "DATA_EXTEND"),
    (USN_REASON_DATA_TRUNCATION, "DATA_TRUNCATION"),
    (USN_REASON_NAMED_DATA_OVERWRITE, "NAMED_DATA_OVERWRITE"),
    (USN_REASON_NAMED_DATA_EXTEND, "NAMED_DATA_EXTEND"),
    (USN_REASON_NAMED_DATA_TRUNCATION, "NAMED_DATA_TRUNCATION"),
    (USN_REASON_FILE_CREATE, "FILE_CREATE"),
    (USN_REASON_FILE_DELETE, "FILE_DELETE"),
    (USN_REASON_EA_CHANGE, "EA_CHANGE"),
    (USN_REASON_SECURITY_CHANGE, "SECURITY_CHANGE"),
    (USN_REASON_RENAME_OLD_NAME, "RENAME_OLD_NAME"),
    (USN_REASON_RENAME_NEW_NAME, "RENAME_NEW_NAME"),
    (USN_REASON_INDEXABLE_CHANGE, "INDEXABLE_CHANGE"),
    (USN_REASON_BASIC_INFO_CHANGE, "BASIC_INFO_CHANGE"),
    (USN_REASON_HARD_LINK_CHANGE, "HARD_LINK_CHANGE"),
    (USN_REASON_COMPRESSION_CHANGE, "COMPRESSION_CHANGE"),
    (USN_REASON_ENCRYPTION_CHANGE, "ENCRYPTION_CHANGE"),
    (USN_REASON_OBJECT_ID_CHANGE, "OBJECT_ID_CHANGE"),
    (USN_REASON_REPARSE_POINT_CHANGE, "REPARSE_POINT_CHANGE"),
    (USN_REASON_STREAM_CHANGE, "STREAM_CHANGE"),
    (USN_REASON_TRANSACTED_CHANGE, "TRANSACTED_CHANGE"),
    (USN_REASON_INTEGRITY_CHANGE, "INTEGRITY_CHANGE"),
    (
        USN_REASON_DESIRED_STORAGE_CLASS_CHANGE,
        "DESIRED_STORAGE_CLASS_CHANGE",
    ),
    (USN_REASON_CLOSE, "CLOSE"),
];

/// Convert a USN reason bitfield to a human-readable string.
pub(super) fn format_reason(reason: u32) -> String {
    let matched: Vec<&'static str> = REASON_FLAGS
        .iter()
        .filter(|(bit, _)| reason & *bit != 0)
        .map(|(_, name)| *name)
        .collect();

    if matched.is_empty() {
        "UNKNOWN".to_string()
    } else {
        matched.join(" | ")
    }
}
